<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<RootNamespace>Yextly.Telemetry.Abstractions</RootNamespace>
		<AssemblyName>Yextly.Telemetry.Abstractions</AssemblyName>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Description>Telemetry abstractions</Description>
		<Authors>$(Company)</Authors>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<IsPackable>true</IsPackable>
	</PropertyGroup>

</Project>
