version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "ignore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"