name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      
      - name: Fix tags
        run: git fetch --prune --unshallow
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run tests
        run: dotnet test

      - name: Prepare release
        id: package_release
        run: |
          OUTPUT=/var/tmp/packages
          echo "OUTPUT=$OUTPUT" >> $GITHUB_ENV
          TAG=`git describe --tags --match v?*`
          VERSION="${TAG:1}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          dotnet build --configuration Release
          dotnet pack --configuration Release /p:PackageOutputPath=$OUTPUT /p:Version=$VERSION

      - name: Publish packages
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" $OUTPUT/*.nupkg

      - name: Create github release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: $GITHUB_TOKEN
          draft: false
          prerelease: false

