name: Test

on: [pull_request, workflow_dispatch]

jobs:
  # build-warnings:
  #   name: Build warnings check
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   steps:
  #     - uses: actions/checkout@v3.2.0

  #     - name: Build
  #       run: dotnet build /WarnAsError

  test:
    name: Tests for framework ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework: ['net6.0', 'net8.0']
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Tests
      run: dotnet test --framework ${{ matrix.framework }}
