// ==++==
//
//   Copyright (c) Shadowsoft Corporation.  All rights reserved.
//
// ==--==

using System.Linq;
using Xunit;

namespace XUnitV3UnitTests
{
    public sealed class TheoryCombiner
    {
        [Fact]
        public void CanCombineTheories()
        {
            var t = new MyTheory();

            var list = t.ToList();

            Assert.Equal(455, list.Count);

            TheoryDataRow a = null!;

            // this call is to avoid the analyzer to stop complaining about the assignment
            Assert.Null(a);

            a = list[0];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[1];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[2];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[3];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[4];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[5];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[6];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[7];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[8];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[9];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[10];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[11];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[12];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[13];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[14];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[15];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[16];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[17];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[18];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[19];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[20];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[21];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[22];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[23];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[24];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[25];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[26];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[27];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[28];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[29];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[30];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[31];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[32];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[33];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[34];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[35];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[36];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[37];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[38];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[39];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[40];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[41];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[42];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[43];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[44];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[45];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[46];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[47];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[48];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[49];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[50];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[51];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[52];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[53];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[54];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[55];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[56];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[57];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[58];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[59];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[60];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[61];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[62];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[63];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[64];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[65];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[66];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[67];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[68];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[69];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[70];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[71];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[72];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[73];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[74];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[75];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[76];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[77];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[78];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[79];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[80];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[81];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[82];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[83];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[84];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[85];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[86];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[87];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[88];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[89];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[90];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(300, (int)a.Data[2]!);
            a = list[91];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[92];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[93];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[94];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[95];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[96];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[97];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[98];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[99];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[100];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[101];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[102];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[103];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[104];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[105];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[106];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[107];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[108];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[109];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[110];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[111];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[112];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[113];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[114];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[115];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[116];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[117];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[118];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[119];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[120];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[121];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[122];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[123];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[124];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[125];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[126];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[127];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[128];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[129];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[130];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[131];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[132];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[133];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[134];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[135];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[136];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[137];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[138];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[139];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[140];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[141];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[142];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[143];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[144];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[145];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[146];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[147];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[148];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[149];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[150];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[151];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[152];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[153];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[154];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[155];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[156];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[157];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[158];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[159];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[160];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[161];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[162];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[163];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[164];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[165];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[166];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[167];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[168];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[169];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[170];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[171];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[172];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[173];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[174];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[175];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[176];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[177];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[178];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[179];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[180];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[181];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(301, (int)a.Data[2]!);
            a = list[182];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[183];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[184];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[185];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[186];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[187];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[188];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[189];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[190];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[191];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[192];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[193];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[194];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[195];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[196];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[197];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[198];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[199];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[200];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[201];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[202];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[203];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[204];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[205];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[206];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[207];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[208];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[209];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[210];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[211];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[212];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[213];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[214];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[215];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[216];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[217];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[218];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[219];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[220];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[221];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[222];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[223];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[224];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[225];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[226];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[227];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[228];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[229];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[230];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[231];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[232];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[233];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[234];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[235];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[236];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[237];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[238];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[239];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[240];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[241];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[242];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[243];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[244];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[245];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[246];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[247];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[248];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[249];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[250];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[251];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[252];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[253];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[254];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[255];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[256];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[257];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[258];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[259];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[260];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[261];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[262];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[263];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[264];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[265];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[266];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[267];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[268];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[269];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[270];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[271];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[272];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(302, (int)a.Data[2]!);
            a = list[273];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[274];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[275];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[276];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[277];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[278];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[279];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[280];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[281];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[282];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[283];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[284];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[285];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[286];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[287];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[288];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[289];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[290];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[291];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[292];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[293];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[294];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[295];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[296];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[297];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[298];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[299];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[300];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[301];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[302];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[303];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[304];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[305];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[306];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[307];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[308];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[309];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[310];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[311];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[312];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[313];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[314];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[315];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[316];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[317];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[318];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[319];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[320];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[321];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[322];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[323];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[324];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[325];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[326];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[327];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[328];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[329];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[330];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[331];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[332];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[333];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[334];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[335];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[336];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[337];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[338];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[339];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[340];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[341];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[342];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[343];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[344];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[345];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[346];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[347];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[348];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[349];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[350];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[351];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[352];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[353];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[354];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[355];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[356];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[357];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[358];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[359];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[360];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[361];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[362];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[363];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(303, (int)a.Data[2]!);
            a = list[364];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[365];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[366];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[367];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[368];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[369];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[370];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[371];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[372];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[373];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[374];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[375];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[376];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(200, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[377];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[378];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[379];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[380];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[381];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[382];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[383];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[384];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[385];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[386];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[387];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[388];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[389];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(201, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[390];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[391];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[392];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[393];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[394];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[395];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[396];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[397];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[398];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[399];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[400];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[401];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[402];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(202, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[403];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[404];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[405];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[406];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[407];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[408];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[409];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[410];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[411];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[412];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[413];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[414];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[415];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(203, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[416];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[417];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[418];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[419];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[420];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[421];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[422];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[423];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[424];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[425];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[426];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[427];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[428];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(204, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[429];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[430];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[431];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[432];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[433];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[434];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[435];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[436];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[437];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[438];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[439];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[440];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[441];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(205, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[442];
            Assert.Equal(100, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[443];
            Assert.Equal(101, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[444];
            Assert.Equal(102, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[445];
            Assert.Equal(103, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[446];
            Assert.Equal(104, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[447];
            Assert.Equal(105, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[448];
            Assert.Equal(106, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[449];
            Assert.Equal(107, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[450];
            Assert.Equal(108, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[451];
            Assert.Equal(109, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[452];
            Assert.Equal(110, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[453];
            Assert.Equal(111, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
            a = list[454];
            Assert.Equal(112, (int)a.Data[0]!);
            Assert.Equal(206, (int)a.Data[1]!);
            Assert.Equal(304, (int)a.Data[2]!);
        }
    }
}
